/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb95f",
        "on-secondary-container": "#00311f",
        "surface-bright": "#31394d",
        "on-tertiary-container": "#6f4500",
        "surface-container-highest": "#2d3449",
        "on-surface": "#dae2fd",
        "surface-container-low": "#131b2e",
        "secondary-container": "#00a572",
        "background": "#0b1326",
        "on-tertiary-fixed": "#2a1700",
        "tertiary-fixed": "#ffddb8",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-tertiary": "#472a00",
        "outline": "#859399",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary-fixed": "#6ffbbe",
        "primary-fixed": "#b7eaff",
        "surface-container-high": "#222a3d",
        "surface-container": "#171f33",
        "tertiary": "#ffd5a5",
        "outline-variant": "#3c494e",
        "surface-variant": "#2d3449",
        "on-surface-variant": "#bbc9cf",
        "tertiary-container": "#ffb044",
        "secondary": "#4edea3",
        "error-container": "#93000a",
        "on-primary-fixed": "#001f28",
        "primary-fixed-dim": "#4cd6ff",
        "on-secondary": "#003824",
        "inverse-surface": "#dae2fd",
        "primary-container": "#00d1ff",
        "on-primary": "#003543",
        "surface": "#0b1326",
        "on-primary-fixed-variant": "#004e60",
        "inverse-primary": "#00677f",
        "on-primary-container": "#00566a",
        "primary": "#a4e6ff",
        "on-background": "#dae2fd",
        "surface-tint": "#4cd6ff",
        "surface-container-lowest": "#060e20",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "inverse-on-surface": "#283044",
        "error": "#ffb4ab",
        "surface-dim": "#0b1326",
        "secondary-fixed-dim": "#4edea3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "2.5rem",
        "container-max": "1200px",
        "margin-mobile": "1rem",
        unit: "4px",
        gutter: "1.5rem",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
